services:
  backend-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: rag-backend-api
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      QDRANT_URL: http://qdrant:6333
      DOCS_DIR: /app/files
    volumes:
      - ./files:/app/files:ro

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: rag-frontend
    depends_on:
      - backend-api
    ports:
      - "5173:80"

  qdrant:
    image: qdrant/qdrant:v1.12.5
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
